import { execFileSync } from "node:child_process";
import { readFileSync } from "node:fs";

const MAX_SBOM_BYTES = 20 * 1024 * 1024;
const failures = [];

function assert(condition, message) {
  if (!condition) {
    failures.push(message);
  }
}

function readJson(file) {
  return JSON.parse(readFileSync(file, "utf8"));
}

function runNpmSbom() {
  try {
    return execFileSync("npm", ["sbom", "--sbom-format", "spdx", "--json", "--package-lock-only"], {
      encoding: "utf8",
      maxBuffer: MAX_SBOM_BYTES,
      stdio: ["ignore", "pipe", "pipe"],
    });
  } catch (error) {
    const stderr = typeof error.stderr === "string" ? error.stderr.trim() : "";
    failures.push(`npm sbom failed${stderr ? `: ${stderr}` : ""}`);
    return "{}";
  }
}

function isRecord(value) {
  return Boolean(value) && typeof value === "object" && !Array.isArray(value);
}

function getPurl(packageEntry) {
  if (!Array.isArray(packageEntry.externalRefs)) {
    return "";
  }

  const purlRef = packageEntry.externalRefs.find((externalRef) => {
    return (
      externalRef.referenceCategory === "PACKAGE-MANAGER" &&
      externalRef.referenceType === "purl" &&
      typeof externalRef.referenceLocator === "string"
    );
  });

  return purlRef?.referenceLocator ?? "";
}

function hasSha512Checksum(packageEntry) {
  return (
    Array.isArray(packageEntry.checksums) &&
    packageEntry.checksums.some((checksum) => {
      return checksum.algorithm === "SHA512" && typeof checksum.checksumValue === "string";
    })
  );
}

console.log("SBOM generation report");

const packageJson = readJson("package.json");
const lockfile = readJson("package-lock.json");
const sbom = JSON.parse(runNpmSbom());

const packages = Array.isArray(sbom.packages) ? sbom.packages : [];
const relationships = Array.isArray(sbom.relationships) ? sbom.relationships : [];
const creators = Array.isArray(sbom.creationInfo?.creators) ? sbom.creationInfo.creators : [];
const lockfilePackages = isRecord(lockfile.packages) ? Object.keys(lockfile.packages) : [];
const lockfilePackageEntries = isRecord(lockfile.packages) ? lockfile.packages : {};
const rootLockfilePackage = isRecord(lockfilePackageEntries[""]) ? lockfilePackageEntries[""] : {};
const directDependencyNames = [
  ...Object.keys(isRecord(rootLockfilePackage.dependencies) ? rootLockfilePackage.dependencies : {}),
  ...Object.keys(isRecord(rootLockfilePackage.devDependencies) ? rootLockfilePackage.devDependencies : {}),
];
const rootPackage = packages.find((packageEntry) => {
  return packageEntry.name === packageJson.name && packageEntry.versionInfo === packageJson.version;
});

assert(sbom.spdxVersion === "SPDX-2.3", "SBOM must use SPDX 2.3 JSON output");
assert(sbom.dataLicense === "CC0-1.0", "SBOM data license must be CC0-1.0");
assert(sbom.name === `${packageJson.name}@${packageJson.version}`, "SBOM document name must match package.json");
assert(typeof sbom.documentNamespace === "string", "SBOM must include a document namespace");
assert(
  creators.some((creator) => /^Tool: npm\/cli-\d+\./.test(creator)),
  "SBOM must be generated by npm CLI",
);
assert(packages.length > directDependencyNames.length, "SBOM must include direct and transitive packages");
assert(
  packages.length <= lockfilePackages.length,
  "SBOM package count must not exceed package-lock.json package count",
);
assert(Boolean(rootPackage), "SBOM must include the root package");

if (rootPackage) {
  assert(
    Array.isArray(sbom.documentDescribes) && sbom.documentDescribes.includes(rootPackage.SPDXID),
    "SBOM document must describe the root package",
  );
  assert(rootPackage.licenseDeclared === packageJson.license, "Root package license must match package.json");
  assert(getPurl(rootPackage) === `pkg:npm/${packageJson.name}@${packageJson.version}`, "Root package purl is wrong");
}

for (const packageEntry of packages) {
  assert(typeof packageEntry.name === "string" && packageEntry.name.length > 0, "Every SBOM package needs a name");
  assert(
    typeof packageEntry.SPDXID === "string" && packageEntry.SPDXID.length > 0,
    "Every SBOM package needs an SPDXID",
  );
  assert(
    typeof packageEntry.versionInfo === "string" && packageEntry.versionInfo.length > 0,
    `${packageEntry.name ?? "unknown package"} must include versionInfo`,
  );
  assert(
    typeof packageEntry.licenseDeclared === "string" && packageEntry.licenseDeclared.length > 0,
    `${packageEntry.name ?? "unknown package"} must include a declared license`,
  );
  assert(
    getPurl(packageEntry).startsWith("pkg:npm/"),
    `${packageEntry.name ?? "unknown package"} must include an npm purl`,
  );

  if (
    typeof packageEntry.downloadLocation === "string" &&
    packageEntry.downloadLocation.startsWith("https://registry.npmjs.org/")
  ) {
    assert(hasSha512Checksum(packageEntry), `${packageEntry.name ?? "unknown package"} must include a SHA512 checksum`);
  }

  const lockfilePath = packageEntry.packageFileName;
  if (lockfilePath) {
    const lockedPackage = lockfilePackageEntries[lockfilePath];

    assert(Boolean(lockedPackage), `${packageEntry.name ?? "unknown package"} must map to package-lock.json`);
    assert(
      !lockedPackage || lockedPackage.version === packageEntry.versionInfo,
      `${packageEntry.name ?? "unknown package"} SBOM version must match package-lock.json`,
    );
  }
}

for (const dependencyName of directDependencyNames) {
  const lockfilePath = `node_modules/${dependencyName}`;
  const lockedPackage = lockfilePackageEntries[lockfilePath];

  assert(Boolean(lockedPackage), `${dependencyName} must be present in package-lock.json`);
  assert(
    packages.some(
      (packageEntry) => packageEntry.name === dependencyName && packageEntry.versionInfo === lockedPackage?.version,
    ),
    `${dependencyName} must be present in the SBOM`,
  );
}

assert(relationships.length > 0, "SBOM must include dependency relationships");

console.log(`- SPDX version: ${sbom.spdxVersion ?? "missing"}`);
console.log(`- package manager: ${creators.join(", ") || "missing"}`);
console.log(`- packages checked: ${packages.length}`);
console.log(`- lockfile packages available: ${lockfilePackages.length}`);
console.log(`- direct dependencies checked: ${directDependencyNames.length}`);
console.log(`- relationships checked: ${relationships.length}`);
console.log(`- root package: ${packageJson.name}@${packageJson.version}`);

if (failures.length > 0) {
  console.error("\nSBOM generation check failed:");
  for (const failure of failures) {
    console.error(`- ${failure}`);
  }
  process.exit(1);
}

console.log("SBOM generation policy passed.");
