import { normalizeSong } from "./storage";
import type { Song, SongEvent } from "./types";

// Built-in practice songs. Every melody here is public domain: traditional
// tunes or works whose composers died well over a century ago (Beethoven,
// arrangements of traditional hymns and folk songs).

export type RawSong = {
  id: string;
  title: string;
  events: SongEvent[];
};

function note(noteId: string, duration: SongEvent["duration"] = "quarter"): SongEvent {
  return { noteIds: [noteId], duration };
}

const RAW_BUILT_IN_SONGS: RawSong[] = [
  {
    id: "builtin-ode-to-joy",
    title: "Ode to Joy (Beethoven)",
    events: [
      note("E4"),
      note("E4"),
      note("F4"),
      note("G4"),
      note("G4"),
      note("F4"),
      note("E4"),
      note("D4"),
      note("C4"),
      note("C4"),
      note("D4"),
      note("E4"),
      note("E4"),
      note("D4"),
      note("D4", "half"),
      note("E4"),
      note("E4"),
      note("F4"),
      note("G4"),
      note("G4"),
      note("F4"),
      note("E4"),
      note("D4"),
      note("C4"),
      note("C4"),
      note("D4"),
      note("E4"),
      note("D4"),
      note("C4"),
      note("C4", "half"),
    ],
  },
  {
    id: "builtin-twinkle-twinkle",
    title: "Twinkle, Twinkle, Little Star",
    events: [
      note("C4"),
      note("C4"),
      note("G4"),
      note("G4"),
      note("A4"),
      note("A4"),
      note("G4", "half"),
      note("F4"),
      note("F4"),
      note("E4"),
      note("E4"),
      note("D4"),
      note("D4"),
      note("C4", "half"),
    ],
  },
  {
    id: "builtin-mary-had-a-little-lamb",
    title: "Mary Had a Little Lamb",
    events: [
      note("E4"),
      note("D4"),
      note("C4"),
      note("D4"),
      note("E4"),
      note("E4"),
      note("E4", "half"),
      note("D4"),
      note("D4"),
      note("D4", "half"),
      note("E4"),
      note("G4"),
      note("G4", "half"),
      note("E4"),
      note("D4"),
      note("C4"),
      note("D4"),
      note("E4"),
      note("E4"),
      note("E4"),
      note("E4"),
      note("D4"),
      note("D4"),
      note("E4"),
      note("D4"),
      note("C4", "whole"),
    ],
  },
  {
    id: "builtin-amazing-grace",
    title: "Amazing Grace",
    events: [
      note("G3"),
      note("C4", "half"),
      note("E4", "eighth"),
      note("C4", "eighth"),
      note("E4", "half"),
      note("D4"),
      note("C4", "half"),
      note("A3"),
      note("G3", "half"),
      note("G3"),
      note("C4", "half"),
      note("E4", "eighth"),
      note("C4", "eighth"),
      note("E4", "half"),
      note("D4"),
      note("G4", "whole"),
    ],
  },
  {
    id: "builtin-when-the-saints",
    title: "When the Saints Go Marching In",
    events: [
      note("C4"),
      note("E4"),
      note("F4"),
      note("G4", "whole"),
      note("C4"),
      note("E4"),
      note("F4"),
      note("G4", "whole"),
      note("C4"),
      note("E4"),
      note("F4"),
      note("G4", "half"),
      note("E4"),
      note("C4"),
      note("E4"),
      note("D4", "whole"),
    ],
  },
  {
    id: "builtin-jingle-bells",
    title: "Jingle Bells (chorus)",
    events: [
      note("E4"),
      note("E4"),
      note("E4", "half"),
      note("E4"),
      note("E4"),
      note("E4", "half"),
      note("E4"),
      note("G4"),
      note("C4"),
      note("D4"),
      note("E4", "whole"),
      note("F4"),
      note("F4"),
      note("F4"),
      note("F4"),
      note("F4"),
      note("E4"),
      note("E4"),
      note("E4", "eighth"),
      note("E4", "eighth"),
      note("E4"),
      note("D4"),
      note("D4"),
      note("E4"),
      note("D4", "half"),
      note("G4", "half"),
    ],
  },
  {
    id: "builtin-yankee-doodle",
    title: "Yankee Doodle",
    events: [
      note("C4"),
      note("C4"),
      note("D4"),
      note("E4"),
      note("C4"),
      note("E4"),
      note("D4"),
      note("G3"),
      note("C4"),
      note("C4"),
      note("D4"),
      note("E4"),
      note("F4"),
      note("E4"),
      note("D4"),
      note("C4"),
      note("B3"),
      note("G3"),
      note("A3"),
      note("B3"),
      note("C4"),
      note("C4"),
      note("C4", "half"),
    ],
  },
  {
    id: "builtin-row-your-boat",
    title: "Row, Row, Row Your Boat",
    events: [
      note("C4"),
      note("C4"),
      note("C4", "eighth"),
      note("D4", "eighth"),
      note("E4"),
      note("E4", "eighth"),
      note("D4", "eighth"),
      note("E4", "eighth"),
      note("F4", "eighth"),
      note("G4", "half"),
      note("C5", "eighth"),
      note("C5", "eighth"),
      note("C5", "eighth"),
      note("G4", "eighth"),
      note("G4", "eighth"),
      note("G4", "eighth"),
      note("E4", "eighth"),
      note("E4", "eighth"),
      note("E4", "eighth"),
      note("C4", "eighth"),
      note("C4", "eighth"),
      note("C4", "eighth"),
      note("G4", "eighth"),
      note("F4", "eighth"),
      note("E4", "eighth"),
      note("D4", "eighth"),
      note("C4", "half"),
    ],
  },
  {
    id: "builtin-silent-night",
    title: "Silent Night",
    events: [
      note("G4", "half"),
      note("A4", "eighth"),
      note("G4", "eighth"),
      note("E4", "half"),
      note("G4", "half"),
      note("A4", "eighth"),
      note("G4", "eighth"),
      note("E4", "half"),
      note("D5", "half"),
      note("D5"),
      note("B4", "half"),
      note("C5", "half"),
      note("C5"),
      note("G4", "half"),
      note("A4", "half"),
      note("A4"),
      note("C5", "eighth"),
      note("B4", "eighth"),
      note("A4"),
      note("G4", "half"),
      note("A4", "eighth"),
      note("G4", "eighth"),
      note("E4", "half"),
    ],
  },
  {
    id: "builtin-greensleeves",
    title: "Greensleeves",
    events: [
      note("D4"),
      note("F4", "half"),
      note("G4"),
      note("A4", "half"),
      note("A#4", "eighth"),
      note("A4", "eighth"),
      note("G4", "half"),
      note("E4"),
      note("C4", "eighth"),
      note("D4", "eighth"),
      note("E4"),
      note("F4", "half"),
      note("D4"),
      note("D4", "eighth"),
      note("C4", "eighth"),
      note("D4", "half"),
      note("E4"),
      note("C4", "half"),
      note("A3"),
      note("D4", "whole"),
    ],
  },
  {
    id: "builtin-frere-jacques",
    title: "Frere Jacques (Are You Sleeping)",
    events: [
      note("C4"),
      note("D4"),
      note("E4"),
      note("C4"),
      note("C4"),
      note("D4"),
      note("E4"),
      note("C4"),
      note("E4"),
      note("F4"),
      note("G4", "half"),
      note("E4"),
      note("F4"),
      note("G4", "half"),
      note("G4"),
      note("A4"),
      note("G4"),
      note("F4"),
      note("E4"),
      note("C4"),
      note("G4"),
      note("A4"),
      note("G4"),
      note("F4"),
      note("E4"),
      note("C4"),
      note("C4"),
      note("G3"),
      note("C4", "half"),
      note("C4"),
      note("G3"),
      note("C4", "half"),
    ],
  },
  {
    id: "builtin-hot-cross-buns",
    title: "Hot Cross Buns",
    events: [
      note("E4"),
      note("D4"),
      note("C4", "half"),
      note("E4"),
      note("D4"),
      note("C4", "half"),
      note("C4"),
      note("C4"),
      note("C4"),
      note("C4"),
      note("D4"),
      note("D4"),
      note("D4"),
      note("D4"),
      note("E4"),
      note("D4"),
      note("C4", "half"),
    ],
  },
  {
    id: "builtin-this-old-man",
    title: "This Old Man",
    events: [
      note("G4"),
      note("E4"),
      note("G4"),
      note("G4"),
      note("A4"),
      note("G4", "half"),
      note("E4"),
      note("G4"),
      note("A4"),
      note("G4"),
      note("E4", "half"),
      note("D4"),
      note("E4"),
      note("F4"),
      note("G4", "whole"),
    ],
  },
  {
    id: "builtin-pop-goes-the-weasel",
    title: "Pop Goes the Weasel",
    events: [
      note("D4"),
      note("G4"),
      note("G4"),
      note("A4"),
      note("G4"),
      note("F4"),
      note("E4", "half"),
      note("D4"),
      note("G4"),
      note("G4"),
      note("A4"),
      note("G4"),
      note("D5", "half"),
      note("B4"),
      note("G4"),
      note("G4"),
      note("F4"),
      note("E4"),
      note("D4", "whole"),
    ],
  },
  {
    id: "builtin-oh-susanna",
    title: "Oh! Susanna (Foster)",
    events: [
      note("C4"),
      note("C4"),
      note("D4"),
      note("E4"),
      note("C4"),
      note("A3"),
      note("A3", "half"),
      note("C4"),
      note("D4"),
      note("E4"),
      note("C4"),
      note("A3"),
      note("G3", "half"),
      note("E4"),
      note("E4"),
      note("D4"),
      note("C4"),
      note("D4"),
      note("E4"),
      note("D4"),
      note("C4"),
      note("A3", "whole"),
    ],
  },
  {
    id: "builtin-camptown-races",
    title: "Camptown Races (Foster)",
    events: [
      note("G4"),
      note("G4"),
      note("E4"),
      note("G4"),
      note("A4"),
      note("G4"),
      note("E4", "half"),
      note("G4"),
      note("G4"),
      note("E4"),
      note("G4"),
      note("A4"),
      note("G4"),
      note("E4", "half"),
      note("D4"),
      note("D4"),
      note("E4"),
      note("D4"),
      note("C4", "whole"),
    ],
  },
  {
    id: "builtin-auld-lang-syne",
    title: "Auld Lang Syne",
    events: [
      note("D4"),
      note("G4"),
      note("G4"),
      note("A4"),
      note("G4"),
      note("E4"),
      note("G4", "half"),
      note("A4"),
      note("G4"),
      note("E4"),
      note("E4"),
      note("D4", "whole"),
      note("D4"),
      note("G4"),
      note("G4"),
      note("A4"),
      note("G4"),
      note("E4"),
      note("D4", "half"),
      note("E4"),
      note("D4"),
      note("B3"),
      note("D4"),
      note("C4", "whole"),
    ],
  },
  {
    id: "builtin-happy-birthday",
    title: "Happy Birthday to You",
    events: [
      note("G4", "eighth"),
      note("G4", "eighth"),
      note("A4"),
      note("G4"),
      note("C5"),
      note("B4", "half"),
      note("G4", "eighth"),
      note("G4", "eighth"),
      note("A4"),
      note("G4"),
      note("D5"),
      note("C5", "half"),
      note("G4", "eighth"),
      note("G4", "eighth"),
      note("G5"),
      note("E5"),
      note("C5"),
      note("B4"),
      note("A4", "half"),
      note("F5", "eighth"),
      note("F5", "eighth"),
      note("E5"),
      note("C5"),
      note("D5"),
      note("C5", "whole"),
    ],
  },
  {
    id: "builtin-old-macdonald",
    title: "Old MacDonald Had a Farm",
    events: [
      note("G4"),
      note("G4"),
      note("G4"),
      note("D4"),
      note("E4"),
      note("E4"),
      note("D4", "half"),
      note("B4"),
      note("B4"),
      note("A4"),
      note("A4"),
      note("G4", "whole"),
      note("D5"),
      note("D5"),
      note("D5"),
      note("G4"),
      note("G4"),
      note("G4"),
      note("D4"),
      note("E4"),
      note("E4"),
      note("D4", "half"),
      note("B4"),
      note("B4"),
      note("A4"),
      note("A4"),
      note("G4", "whole"),
    ],
  },
  {
    id: "builtin-fur-elise",
    title: "Fur Elise, opening (Beethoven)",
    events: [
      note("E5", "eighth"),
      note("D#5", "eighth"),
      note("E5", "eighth"),
      note("D#5", "eighth"),
      note("E5", "eighth"),
      note("B4", "eighth"),
      note("D5", "eighth"),
      note("C5", "eighth"),
      note("A4", "half"),
      note("C4", "eighth"),
      note("E4", "eighth"),
      note("A4", "eighth"),
      note("B4", "half"),
      note("E4", "eighth"),
      note("G#4", "eighth"),
      note("B4", "eighth"),
      note("C5", "half"),
    ],
  },
];

export function buildBuiltInSongs(rawSongs: RawSong[]): Song[] {
  return rawSongs.map((raw) => {
    const song = normalizeSong(raw, "builtin");
    if (!song) {
      throw new Error(`Built-in song failed validation: ${raw.id}`);
    }
    return song;
  });
}

export const BUILT_IN_SONGS: Song[] = buildBuiltInSongs(RAW_BUILT_IN_SONGS);

export function getSongById(songs: Song[], songId: string): Song | undefined {
  return songs.find((song) => song.id === songId);
}
